#Author: Avery Cordle
import turtle

turtle.bgcolor("skyblue")
turtle.setup(500,500)
pen = turtle.Turtle()
pen.pensize(2)
pen.speed(5)

#draw an apple tree
#draw the trunk
pen.penup()
pen.fillcolor("brown")
pen.begin_fill()
pen.setpos(-40,-150)
pen.pendown()
pen.forward(80)
pen.left(90)
pen.forward(150)
pen.left(90)
pen.forward(80)
pen.left(90)
pen.forward(150)
pen.left(90)
pen.end_fill()

#draw the leaves
pen.penup()
pen.setheading(90)
pen.forward(100)
pen.setheading(360)
pen.forward(40)
pen.fillcolor("green")
pen.begin_fill()
pen.pendown()
pen.circle(100)
pen.end_fill()

#draw the apples
pen.penup()
pen.setheading(50)
pen.forward(50)
pen.setheading(0)
pen.fillcolor("red")
pen.begin_fill()
pen.pendown()
pen.circle(10)
pen.end_fill()
#make the stem
pen.penup()
pen.setheading(90)
pen.forward(20)
pen.setheading(360)
pen.forward(5)
pen.setheading(90)
pen.fillcolor("brown")
pen.begin_fill()
pen.pendown()
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.end_fill()

#more apples!
pen.penup()
pen.setpos(20,100)
pen.setheading(360)
pen.fillcolor("red")
pen.begin_fill()
pen.pendown()
pen.circle(10)
pen.end_fill()
#make the stem
pen.penup()
pen.setheading(90)
pen.forward(20)
pen.setheading(360)
pen.forward(5)
pen.setheading(90)
pen.fillcolor("brown")
pen.begin_fill()
pen.pendown()
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.end_fill()

#even more apples :)
pen.penup()
pen.setpos(-50,40)
pen.setheading(360)
pen.fillcolor("red")
pen.begin_fill()
pen.pendown()
pen.circle(10)
pen.end_fill()
#make the stem
pen.penup()
pen.setheading(90)
pen.forward(20)
pen.setheading(360)
pen.forward(5)
pen.setheading(90)
pen.fillcolor("brown")
pen.begin_fill()
pen.pendown()
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.end_fill()

#one last apple
pen.penup()
pen.setpos(-60,-150)
pen.setheading(360)
pen.fillcolor("red")
pen.begin_fill()
pen.pendown()
pen.circle(10)
pen.end_fill()
#make the stem
pen.penup()
pen.setheading(90)
pen.forward(20)
pen.setheading(360)
pen.forward(5)
pen.setheading(90)
pen.fillcolor("brown")
pen.begin_fill()
pen.pendown()
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.end_fill()





turtle.done()